[workspace]
members = ["dist:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.24.0-prerelease.2"
# CI backends to support
ci = "github"
# Which actions to run on pull requests
pr-run-mode = "upload"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
github-build-setup = "../build-setup.yml"
